name: CI

on:
  pull_request:
    branches: [master]

jobs:
  # Run basic tests.
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 12.18.3
      - name: Install Packages
        run: npm install
      - name: Run Tests
        run: npm build
      - name: Run Backend Tests
        run: npm test 
